# SPDX-License-Identifier: AGPL-3.0-or-later
"""Shared MCP + SACP error codes. Spec 030 Phase 2, FR-019 + FR-055."""

# JSON-RPC 2.0 standard codes
JSONRPC_PARSE_ERROR = -32700
JSONRPC_INVALID_REQUEST = -32600
JSONRPC_METHOD_NOT_FOUND = -32601
JSONRPC_INVALID_PARAMS = -32602
JSONRPC_INTERNAL_ERROR = -32603

# SACP server-defined codes (FR-019)
SACP_AUTH_FAILED = -32001
SACP_RATE_LIMIT = -32002
SACP_STATE_ERROR = -32003

# SACP error code strings (FR-055)
SACP_E_VALIDATION = "SACP_E_VALIDATION"
SACP_E_FORBIDDEN = "SACP_E_FORBIDDEN"
SACP_E_NOT_FOUND = "SACP_E_NOT_FOUND"
SACP_E_INTERNAL = "SACP_E_INTERNAL"
SACP_E_AUTH = "SACP_E_AUTH"
SACP_E_RATE_LIMIT = "SACP_E_RATE_LIMIT"
SACP_E_SESSION_EXPIRED = "SACP_E_SESSION_EXPIRED"
SACP_E_STEP_UP_REQUIRED = "SACP_E_STEP_UP_REQUIRED"
SACP_E_DEPRECATED = "SACP_E_DEPRECATED"
